version: '3'

services:
  gateway:
    depends_on:
      - tasklists
      - wallets
    build:
      context: ./gateway
      dockerfile: ./gateway.dockerfile
    ports:
      - 5000:3000
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file: ./gateway/.env

  tasklists:
    build:
      context: ./tasklists
      dockerfile: ./tasklists.dockerfile
    expose:
      - 3001
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file: ./tasklists/.env

  wallets:
    build:
      context: ./wallets
      dockerfile: ./wallets.dockerfile
    expose:
      - 3002
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file: ./wallets/.env